name: phi543
channels:
  - conda-forge
dependencies:
  - python
  - seaborn
  - tensorflow
  - tensorflow-datasets
  - scikit-learn
  - pandas
  - scipy
  - pip
  - pip:
    - keras-cv
    - keras-nlp
