name: phi543
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - seaborn
    - scikit-learn
    - pandas
    - scipy
    - tensorflow-cpu
    - tensorflow-datasets
    - pycocotools
    - keras-cv
    - keras-nlp
